version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@textlint/markdown-to-ast"
    versions:
    - 6.3.1
    - 6.3.2
    - 6.3.3
  - dependency-name: ejs
    versions:
    - 3.1.5
